# Generated by Django 5.1.1 on 2024-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(default='Null', max_length=254),
        ),
    ]
