# Generated by Django 5.1.1 on 2024-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_alter_appointment_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
